//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn2121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int ExpenditureID { get; set; }
        public int ServiceID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Expenditure1 { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
    }
}
