//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn2121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performed
    {
        public int PerformedID { get; set; }
        public int ClientID { get; set; }
        public int EmployeeID { get; set; }
        public int LocationID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
        public virtual Service Service { get; set; }
    }
}
