//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn2121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int EmployeeID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
